import type { Metadata } from "next";
import "./globals.css";
import { Raleway, Fira_Code } from "next/font/google";
import localfont from "next/font/local";

const neueMachina = localfont({
  src: [
    {
      path: "fonts/NeueMachina-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/NeueMachina-Ultrabold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-neue-machina",
});
const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal"],
  variable: "--raleway-font",
});
const firaCode = Fira_Code({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal"],
  variable: "--fira-code-font",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${neueMachina.variable} ${firaCode.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
